name: Jest

on:
  pull_request:
  push:

jobs:
  run-jest:
    name: jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: c-hive/gha-npm-cache@v1
      - name: Jest Code Coverage Report
        uses: ziishaned/jest-reporter-action@0.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: 'npm run test:cov'
